# Generated by Django 5.1.4 on 2025-02-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_skills_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='performance_score',
            field=models.FloatField(default=0.0),
        ),
    ]
