# Generated by Django 5.1.4 on 2025-02-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventRecord', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='draft_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
    ]
