# Generated by Django 5.1.4 on 2025-02-20 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventRecord', '0002_report_draft_content_report_is_draft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='draft_content',
        ),
        migrations.RemoveField(
            model_name='report',
            name='is_draft',
        ),
    ]
