# Generated by Django 5.1.4 on 2025-02-28 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventRecord', '0003_remove_report_draft_content_remove_report_is_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EventRecord.report'),
        ),
    ]
